///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String iconsBeef = 'assets/icons/beef.png';
  static const String iconsCheese = 'assets/icons/cheese.png';
  static const String iconsChicken = 'assets/icons/chicken.png';
  static const String iconsVegetable = 'assets/icons/vegetable.png';

}
